/**
 * Worktree (and matching git branch) name generator. Produces a Pokémon
 * name plus a 2-digit suffix, e.g. `pikachu-42`, `charizard-08`. Collision
 * probability stays low across a single project; `WorktreeService.create`
 * retries on duplicates.
 */
const POKEMON = [
  "bulbasaur",
  "ivysaur",
  "venusaur",
  "charmander",
  "charmeleon",
  "charizard",
  "squirtle",
  "wartortle",
  "blastoise",
  "caterpie",
  "butterfree",
  "weedle",
  "beedrill",
  "pidgey",
  "pidgeotto",
  "pidgeot",
  "rattata",
  "spearow",
  "ekans",
  "pikachu",
  "raichu",
  "sandshrew",
  "nidoran",
  "clefairy",
  "vulpix",
  "ninetales",
  "jigglypuff",
  "zubat",
  "golbat",
  "oddish",
  "gloom",
  "vileplume",
  "paras",
  "venonat",
  "diglett",
  "meowth",
  "persian",
  "psyduck",
  "golduck",
  "mankey",
  "primeape",
  "growlithe",
  "arcanine",
  "poliwag",
  "abra",
  "kadabra",
  "alakazam",
  "machop",
  "machoke",
  "machamp",
  "tentacool",
  "geodude",
  "graveler",
  "golem",
  "ponyta",
  "rapidash",
  "slowpoke",
  "magnemite",
  "farfetchd",
  "doduo",
  "seel",
  "grimer",
  "shellder",
  "gastly",
  "haunter",
  "gengar",
  "onix",
  "drowzee",
  "krabby",
  "voltorb",
  "exeggcute",
  "cubone",
  "marowak",
  "hitmonlee",
  "hitmonchan",
  "lickitung",
  "koffing",
  "rhyhorn",
  "chansey",
  "tangela",
  "kangaskhan",
  "horsea",
  "goldeen",
  "staryu",
  "scyther",
  "jynx",
  "electabuzz",
  "magmar",
  "pinsir",
  "tauros",
  "magikarp",
  "gyarados",
  "lapras",
  "ditto",
  "eevee",
  "vaporeon",
  "jolteon",
  "flareon",
  "porygon",
  "omanyte",
  "kabuto",
  "snorlax",
  "dragonite",
  "mewtwo",
  "mew",
] as const;

const pick = <T>(list: readonly T[]): T =>
  list[Math.floor(Math.random() * list.length)]!;

export const generateCoolName = (): string => {
  const suffix = Math.floor(Math.random() * 90 + 10); // 10..99
  return `${pick(POKEMON)}-${suffix}`;
};
